// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSRjhT22oATY6hGOxRTeMxVwvRu8QsjKk',
    appId: '1:969675850397:web:17b32f7020271ca07fca74',
    messagingSenderId: '969675850397',
    projectId: 'massar-bus-system',
    authDomain: 'massar-bus-system.firebaseapp.com',
    storageBucket: 'massar-bus-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-vXMtbj77586Zdno2KVqoR2dlOtDhDFQ',
    appId: '1:969675850397:android:9253976f2d8ab0d77fca74',
    messagingSenderId: '969675850397',
    projectId: 'massar-bus-system',
    storageBucket: 'massar-bus-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjvQrjs7_9JJz4eui6dWIdm6YD2rY8XX4',
    appId: '1:969675850397:ios:44218e65f115e5a37fca74',
    messagingSenderId: '969675850397',
    projectId: 'massar-bus-system',
    storageBucket: 'massar-bus-system.firebasestorage.app',
    iosClientId: '969675850397-a3jbfmqramn41iqnt2frkj3t5somghl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.massarProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjvQrjs7_9JJz4eui6dWIdm6YD2rY8XX4',
    appId: '1:969675850397:ios:44218e65f115e5a37fca74',
    messagingSenderId: '969675850397',
    projectId: 'massar-bus-system',
    storageBucket: 'massar-bus-system.firebasestorage.app',
    iosClientId: '969675850397-a3jbfmqramn41iqnt2frkj3t5somghl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.massarProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSRjhT22oATY6hGOxRTeMxVwvRu8QsjKk',
    appId: '1:969675850397:web:4645f3c01ef7e3647fca74',
    messagingSenderId: '969675850397',
    projectId: 'massar-bus-system',
    authDomain: 'massar-bus-system.firebaseapp.com',
    storageBucket: 'massar-bus-system.firebasestorage.app',
  );
}


